[package]
name = "quic"
version = "0.1.0"
edition = "2024"

[dependencies]
# tokio = { version = "=1.52.3", features = ["full"] }
# socket2 = "=0.6.4"
# rustls = { version = "=0.23.41", default-features = false, features = [] }

# [features]
# ring = ["rustls/ring"]
# aws-lc-rs = ["rustls/aws-lc-rs"]
